Aagarwal/application routing
Brightspace/content-service-viewer pull request #46
Opened 2023-09-14 07:00 UTC by aagarwal-d2l

2023-09-14 12:47 UTC, dchopkar requested changes

2023-09-14 12:47 UTC, dchopkar commented on src/components/Framework/Instances/Activity-Instance-users.js
> +		const url = instance.href.split('https://us-east-1.creator-platform.api.dev.brightspace.com/1')[1];
Please create constant for base url

2023-09-14 12:47 UTC, dchopkar commented on src/components/Framework/Instances/Completion-summary/assigned-activity-instance.js
> +		// const event = new CustomEvent('list-item-clicked-parent', {
remove commented code, from all over places

2023-09-14 12:47 UTC, dchopkar commented on src/routes.js
> +		view: (ctx) => { return html`<activities-container  token="${ctx.options.token}" href="${`https://us-east-1.creator-platform.api.dev.brightspace.com/1${ctx.path}`}" ></activities-container>`;}
create constant file for base Url

2023-09-14 13:06 UTC, syedabbasD2L commented on src/components/Framework/Instances/Collections/InstanceTreeViewListItem.js
> +				this.instanceHref = this._entity?.getLinkByRel('https://activities.api.brightspace.com/rels/member-instance')?.href;
use constant from constant file

2023-09-14 13:07 UTC, syedabbasD2L commented on src/components/Framework/Instances/Completion-summary/assigned-activity-instance.js
> +		const url = list.href.split('https://us-east-1.creator-platform.api.dev.brightspace.com/1')[1];
use constant from constant file check other places as well

2023-09-14 13:08 UTC, syedabbasD2L commented on src/components/Framework/main-activity-list/index.js
> +		this.href = 'https://us-east-1.creator-platform.api.dev.brightspace.com/1/activities';
use constant from constant file

2023-09-14 13:08 UTC, syedabbasD2L commented on src/components/Framework/main-activity-list/main-activity-list.js
> +		const url = e.detail.split('https://us-east-1.creator-platform.api.dev.brightspace.com/1')[1];
use constant from constant file

2023-09-15 11:47 UTC, dchopkar approved these changes

2023-09-15 11:48 UTC, merged