Syed/editcollection addactivity
Brightspace/content-service-viewer pull request #58
Opened 2023-09-25 09:48 UTC by syedabbasD2L

2023-09-25 10:14 UTC, aagarwal-d2l commented on src/components/Framework/AddActvities/EditCollectionAddActivity.js
> +            <div style="width:50%">
@syedabbasD2L  please use class

2023-09-25 10:14 UTC, aagarwal-d2l commented on src/components/Framework/AddActvities/EditCollectionAddActivity.js
> +         @click=${(e) => {this.isProviderClick = false;}}>Back</d2l-button>
@syedabbasD2L  dont use arrow function here

2023-09-25 10:14 UTC, aagarwal-d2l commented on src/components/Framework/AddActvities/EditCollectionAddActivity.js
> +        @provider-click ="${(e) => this._handleProviderClick(e.detail)}">
@syedabbasD2L  Please remove all arrow function

2023-09-25 12:08 UTC, dchopkar requested changes

2023-09-25 12:08 UTC, dchopkar commented on src/components/Framework/Activities/Collections/EditCollectionTreeViewListItem.js
> +		await fetch(this.updateActivityFormBodyToggle.href, {
use **performAction** method instead of fetch from entity mixin

2023-09-27 11:00 UTC, dchopkar requested changes

2023-09-27 11:10 UTC, dchopkar approved these changes

2023-09-27 11:10 UTC, merged